dist: xenial

language: php

php:
  - 7.2

cache:
  directories:
    - node_modules
    - vendor

before_script:
  - composer self-update
  - composer install --no-interaction

script:
  - vendor/bin/phpunit
